# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - uses: pypa/hatch@install
      - name: Check lint and format
        run: |
          hatch fmt --check
      - name: Type-checking with Mypy
        run: |
          hatch run types:check
      - name: Run tests with pytest
        run: |
          hatch run +py=${{ matrix.python-version }} all:test-cov -- junitxml=junit-${{ matrix.python-version }}.xml -o junit_family=legacy
      - name: Upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
