# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: typing-and-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: pypa/hatch@install
      - name: Check lint and format
        run: |
          hatch fmt --check
      - name: Type-checking with Mypy
        run: |
          hatch run types:check
      - name: Run tests with pytest
        run: |
          hatch run +py=${{ matrix.python-version }} all:test-cov \
          --cov-report=xml:coverage-${{ matrix.python-version }}.xml
      - name: Coveralls upload
        if: ${{ !cancelled() }}
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage-*.xml
          fail-on-error: true
          parallel: true